---

- src: santiagomr.ssh_server
  # src: https://github.com/santiagomr/ansible-role-ssh-server.git
  # scm: git

- src: oefenweb.fail2ban
  # src: https://github.com/Oefenweb/ansible-fail2ban.git
  # scm: git

- src: oefenweb.ufw
  # src: https://github.com/Oefenweb/ansible-ufw.git
  # scm: git
