# defaults file for ufw
---
ufw_default_incoming_policy: deny
ufw_default_outgoing_policy: allow

ufw_logging: 'off'

ufw_rules:
  - rule: allow
    interface: "{{ ansible_default_ipv4['interface'] }}"
    to_port: "{{ ssh_server_listen_port }}"
    protocol: tcp

      # HTTP/HTTPS from any interface
  - rule: allow
    to_port: 80
    protocol: tcp
  - rule: allow
    to_port: 443
    protocol: tcp

      # Any protocol. TCP and UDP
  - rule: allow
    to_port: 53

      # Only from an internal network
  - rule: allow
    to_port: 8080
    from_ip: 10.100.0.0/16
    protocol: tcp

# /etc/default/ufw
ufw_etc_default_ipv6: true
ufw_etc_default_default_input_policy: DROP
ufw_etc_default_default_output_policy: ACCEPT
ufw_etc_default_default_forward_policy: DROP
ufw_etc_default_default_application_policy: SKIP
ufw_etc_default_manage_builtins: false
ufw_etc_default_ipt_sysctl: /etc/ufw/sysctl.conf
ufw_etc_default_ipt_modules:
  - nf_conntrack_ftp
  - nf_nat_ftp
  - nf_conntrack_netbios_ns
