---
# tasks file for ssh_server

- name: Set ssh server config file
  template:   # https://docs.ansible.com/ansible/latest/modules/template_module.html
    src: sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: "0644"
  notify: reload ssh server

- name: Set motd
  copy:
    src: "etc/motd/{{ inventory_hostname.split('.')[0] }}"
    dest: "/etc/motd"
    owner: root
    group: root
    mode: "0644"